### ISSUE TITLE
FEAT: Import a library ([starknet::component]) inside another library ([starknet::component]) #1403

### ISSUE THREAD

**Issue by Cevedale** [foundry-rs/starknet-foundry#1404] opened 2023-12-18 09:12 UTC
### Which component is your feature related to?

Forge

### Feature Request

Take a look at the file paths for both the 'LibAsset' and 'LibFees', check the export, it should look like that:
export { LibAsset };
When you try to import the 'LibAsset' , check the statement:
import { LibAsset } from 'path/to/LibAsset';
Your module resolution configuration should be set up correctly. For example, in a TypeScript project, check the tsconfig.json file for proper configuration.
Let me know if you found it useful

**Comment by Arcticae** [comment] 2023-12-18 09:21
Duplicate of #1403

**Closed by Arcticae** 2023-12-18 09:21 UTC
Labels: new
