### ISSUE TITLE
Move test running logic and hint processor to a separate crate, under `snforge-core` team responsibility

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#679] opened 2023-09-18 11:19 UTC

**Comment by MaksymilianDemitraszek** [comment] 2023-10-05 12:47
I think it should happen. Forge crate mixes to many responsibilities

**Comment by Arcticae** [comment] 2023-11-07 11:38
Duplicate of #839

**Closed by Arcticae** 2023-11-07 11:38 UTC
Labels: Team: snforge-core
