### ISSUE TITLE
Display max_fee as decimal

### ISSUE THREAD

**Issue by drknzz** [foundry-rs/starknet-foundry#410] opened 2023-08-04 10:24 UTC
### To what component is your bug related to?

Cast

### Feature Request

```bash
$ sncast account create --name my_account

Account successfully created. Prefund generated address with at least 4323008256930 tokens. It is good to send more in the case of higher demand, max_fee * 2 = 8646016513860
command: account create
add_profile: --add-profile flag was not set. No profile added to Scarb.toml
address: 0x3e5b320468ce80d69fe69e2011f80065cf41298ac18a76a124f14849c3d29e9
max_fee: 0x3ee875f1ba2
```

max_fee should be displayed in decimal form, the same way it is displayed in the message above

```bash
address: 0x3e5b320468ce80d69fe69e2011f80065cf41298ac18a76a124f14849c3d29e9
max_fee: 4323008256930
```

Possibly a flag similar to `--int-format`, should be added to display every output in hex format.

**Comment by binsta** [comment] 2023-08-08 00:06
can i take this one

**Comment by drknzz** [comment] 2023-08-08 06:52
> can i take this one

Sure, just confirm that you want to do it and you will be assigned 👍 

I guess the flag should be called `--hex-format`.

**Comment by Gathin23** [comment] 2023-08-16 15:54
Is there any progress or can I take up the issue?

**Comment by drknzz** [comment] 2023-08-18 13:14
Hey, @binsta please let us know if you're still interested in this issue.

**Comment by binsta** [comment] 2023-08-19 00:31
@drknzz you may assign it to @Gathin23 . I'll take another issue.

**Comment by dhruvdabhi101** [comment] 2023-08-20 13:55
If this issue is open, then i would like to contribute.

**Comment by Gathin23** [comment] 2023-08-21 12:54
I would like to try solving it

**Comment by dhruvdabhi101** [comment] 2023-08-21 17:20
https://github.com/foundry-rs/starknet-foundry/blob/8f82b12c50b6b8df9cc74b1abd0c64ad15421fdc/crates/cast/src/starknet_commands/account/create.rs#L22

Maybe you need to add one property in this struct `hex_format`. and do accordingly. Correct me if i'm missing something.

**Comment by Gathin23** [comment] 2023-08-21 18:24
> 

Sure will do !

**Comment by Gathin23** [comment] 2023-08-21 18:27
I guess you could take up this issue @cptartur could you assign this to @dhruvdabhi101

**Comment by THenry14** [comment] 2023-08-30 10:56
Hi @dhruvdabhi101 ! 
Hope everything's going well! Just wanted to touch base regarding this issue. If you need any input, run into questions, or would like to discuss anything, feel free to reach out. We're here to support you if you run on any blockers :) cheers!

**Comment by THenry14** [comment] 2023-09-07 10:47
Hi @dhruvdabhi101 , haven't heard from you in a while so for now I'm going to unassign you from this issue, so it is not blocked for others. If you'd still like to work on this please let me know, and if the issue is still available I'll re-assign you :)

**Comment by dhruvdabhi101** [comment] 2023-09-07 10:56
Ohh yeah, i'm really sorry, i have exams going on right now, i won't be able to work on this issue. sorry for taking up these much time. :(

**Comment by THenry14** [comment] 2023-09-07 10:56
No problem :) Good luck on your exams!

**Comment by lambda-0x** [comment] 2023-09-28 14:41
i can help with this one!

**Comment by cptartur** [comment] 2023-09-28 14:59
Sure, assigning!

**Comment by cptartur** [comment] 2023-09-28 15:54
I think default should be decimal, but I'll let the Cast team explain it better: @THenry14 @drknzz what do you think?

**Comment by THenry14** [comment] 2023-09-29 07:13
@lambda-0x yup, dec should be the default, possibly changed with --hex-format :+1:

**Closed** 2023-10-24 13:31 UTC
Labels: good first issue, Team: chain-interactions, feature
