### ISSUE TITLE
Introduce `pub` keywords in `snforge_std` (requires changing edition to `2023_11`)

### ISSUE THREAD

**Issue by piotmag769** [foundry-rs/starknet-foundry#1585] opened 2024-01-24 08:22 UTC
### Which components does the task require to be changed? (think hard pls)

snforge

### Description

https://community.starknet.io/t/cairo-v2-5-0-is-out/112807#the-pub-keyword-9

**Comment by Arcticae** [comment] 2024-05-22 15:08
Duplicate of #1888

**Closed by Arcticae** 2024-05-22 15:08 UTC
Labels: Team: snforge
