### ISSUE TITLE
Investigate asynchronous rpc request for forks

### ISSUE THREAD

**Issue by cptartur** [foundry-rs/starknet-foundry#792] opened 2023-10-03 12:44 UTC
Blocked by #663 
It should be a shared state between different tests, which relies on some workers already having fetched some data.
It's an optimization and is not high prio

**Comment by Arcticae** [comment] 2023-10-13 10:54
Currently blocked because async execution architecture is not stable

**Comment by Arcticae** [comment] 2024-03-05 14:41
Duplicate of #901

**Closed by Arcticae** 2024-03-05 14:41 UTC
Labels: blocked, Team: snforge
