### ISSUE TITLE
Automatically create a tag after release PR was merged

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [foundry-rs/starknet-foundry#867] opened 2023-10-12 07:00 UTC
Implement this (or similar) flow:

1. Creating a PR that bumps project version in `Cargo.toml` triggers a workflow
2. New tag is automatically created
3. Build is started
4. After build is finished, create a new release on GH with changelog generated automatically from CHANGELOG.md file

CHANGELOG.md should be updated at some step so that "Unreleased" section is converted to a new version and a new "Unreleased" section is created. Ideally this modification to changelog should be contained both on the master branch and newly created tag.

**Comment by cptartur** [comment] 2023-10-13 10:27
Duplicate of #859

**Closed by cptartur** 2023-10-13 10:27 UTC
Labels: Team: snforge-cli
