### ISSUE TITLE
Automatic free RPC vendor configuration 

### ISSUE THREAD

**Issue by ksew1** [foundry-rs/starknet-foundry#2315] opened 2024-07-17 09:26 UTC
### Which component is your feature related to?

Cast

### Feature Request

- We should automatically configure free RPC vendor to provide out of the box experience. 

- We can use this providers: 
    * [Blast](https://blastapi.io/public-api/starknet)
    * [Nethermind](https://data.voyager.online/)
    
- As this could be implemented in many ways, please start with design-doc

**Comment by Arcticae** [comment] 2024-08-02 11:47
Duplicate of #2212

**Closed by Arcticae** 2024-08-02 11:47 UTC
Labels: Team: sncast, new, design-doc
