### ISSUE TITLE
Sncast do not work with correct configure of snfoundry.toml

### ISSUE THREAD

**Issue by Xor0v0** [foundry-rs/starknet-foundry#1984] opened 2024-04-06 16:50 UTC
### Which component is your bug related to?

sncast

### Foundry Version

v0.17.0~v0.21.0

### What operating system are you using?

MacOS

### What system architecture are you using?

arm

### What happened

I am trying to use `sncast` but it did not work even with the same configure in the starknet foundry book.

The following is my `snfoundry.toml` configure information:

```toml
[sncast.default]
account = "Xor0v0"
accounts-file = "~/my-starknet-accounts/account.json"
url = "https://rpc.nethermind.io/sepolia-juno?apikey=rpc_key"
# url = "https://starknet-mainnet.infura.io/v3/rpc_key"
# url = "https://starknet-mainnet.g.alchemy.com/v2/rpc_key"
```

When I try to call a contract function with following command:

```bash
sncast call \
--contract-address 0x01a730fb914b6e79e6e05af2996b423306652c1c2d5036a455f3979d20161c8f \
--function get_owner \
--block-id latest
```
It return : `Error: RPC url not passed nor found in snfoundry.toml`. But instead I use command:

```bash
sncast -u https://rpc.nethermind.io/sepolia-juno?apikey=rpc_key call \
--contract-address 0x01a730fb914b6e79e6e05af2996b423306652c1c2d5036a455f3979d20161c8f \
--function get_owner \
--block-id latest
```

it return the expected result: `command: call
response: [0x5b54a13bfc88......cbd4d6938e907]`

As you can see, I have tried many solutions: different networks (mainnet and sepolia), different rpc(nethermind, infura, alchemy) endpoints and even snfoundry version from `0.17.0` to `0.21.0` (latest).  They all get the bad response. 

### Trace

`Error: RPC url not passed nor found in snfoundry.toml`

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment] 2024-04-19 11:33
Hi, @Xor0v0 , sadly I cannot reproduce the issue you've described. Can you tell me something more about your setup? 
My guess is maybe snfoundry.toml is not present in the current/parent directory, and because of that the url cannot be properly determined? Can you show me your directory layout and exact commands (with an information about current working directory)? Alternatively, are you able to provide some repro code I could use to try to debug it further locally on my machine? thanks!

**Comment by THenry14** [comment] 2024-04-26 11:52
Closing an issue since it seems it might have been an user error. If you think this is not the case, and are able to provide repro code, feel free to re-open and provide the necessary info to reproduce the error. Thanks!

**Closed by THenry14** 2024-04-26 11:52 UTC
Labels: bug, Team: chain-interactions
