### ISSUE TITLE
Remove dependency on Scarb's CASM output

### ISSUE THREAD

**Issue by Arcticae** [foundry-rs/starknet-foundry#1213] opened 2023-11-27 14:04 UTC
Blocked by [1212](https://github.com/foundry-rs/starknet-foundry/issues/1212)

We should not use Scarb's CASM outputs since they are only for preview/debug purposes

**Comment by cptartur** [comment] 2023-11-28 15:19
Duplicate of #1140

**Closed by cptartur** 2023-11-28 15:19 UTC
Labels: blocked, Team: snforge-cli, new
